name: flutter_socks5_proxy
description: A Flutter package for easy SOCKS5 proxy configuration with simple connect/disconnect API.
version: 1.0.1
homepage: https://github.com/bear2u/flutter_socks5_proxy2
repository: https://github.com/bear2u/flutter_socks5_proxy2
issue_tracker: https://github.com/bear2u/flutter_socks5_proxy2/issues

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_socks5_proxy
        pluginClass: FlutterSocks5ProxyPlugin
        